steps:
# https://github.com/GoogleCloudPlatform/cloud-sdk-docker
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:364.0.0'
  entrypoint: 'echo'
  args:
    - 'hi cloud build'

# https://github.com/hashicorp/terraform
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.10'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform init -no-color
  env:
  - 'TF_VAR_project=$PROJECT_ID'

- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.10'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      terraform plan -no-color
  env:
  - 'TF_VAR_project=$PROJECT_ID'

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.10'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [ "master" = "$BRANCH_NAME" ]; then
        terraform apply -auto-approve -no-color
      else
        echo "***************************** SKIPPING APPLYING *******************************"
        echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
        echo "*******************************************************************************"
      fi
  env:
  - 'TF_VAR_project=$PROJECT_ID'
        
# so the service account doesn't need storage roles / specify bucket
options:
  logging: CLOUD_LOGGING_ONLY