steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - 'echo'
    - 'hi cloud build'
# so the service account doesn't need storage roles
options:
  logging: CLOUD_LOGGING_ONLY